export interface ProductType {
  id: number;
  imageUrl: string;
  name: string;
  price: number;
  productType: string;
  quantity?: number;
}

export const AllProductTypes: string[] = [
  'hats',
  'jackets',
  'sneakers',
  'mens',
  'womans',
];

export const Products: ProductType[] = [
  {
    imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
    id: 1,
    name: 'Brown Brim',
    price: 25,
    productType: 'hats',
  },
  {
    price: 18,
    id: 2,
    imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
    name: 'Blue Beanie',
    productType: 'hats',
  },
  {
    name: 'Brown Cowboy',
    id: 3,
    imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
    price: 35,
    productType: 'hats',
  },
  {
    imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
    id: 4,
    name: 'Grey Brim',
    price: 25,
    productType: 'hats',
  },
  {
    name: 'Green Beanie',
    id: 5,
    price: 18,
    imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
    productType: 'hats',
  },
  {
    imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
    id: 6,
    price: 14,
    name: 'Palm Tree Cap',
    productType: 'hats',
  },
  {
    price: 18,
    id: 7,
    imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
    name: 'Red Beanie',
    productType: 'hats',
  },
  {
    imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
    name: 'Wolf Cap',
    id: 8,
    price: 14,
    productType: 'hats',
  },
  {
    imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
    id: 9,
    name: 'Blue Snapback',
    price: 16,
    productType: 'hats',
  },

  {
    id: 18,
    price: 125,
    name: 'Black Jean Shearing',
    imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
    productType: 'jackets',
  },
  {
    id: 19,
    imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
    name: 'Blue Jean Jacket',
    price: 90,
    productType: 'jackets',
  },
  {
    name: 'Grey Jean Jacket',
    id: 20,
    price: 90,
    imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
    productType: 'jackets',
  },
  {
    imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
    name: 'Brown Shearing',
    price: 165,
    id: 21,
    productType: 'jackets',
  },
  {
    price: 185,
    id: 22,
    imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
    name: 'Tan Trench',
    productType: 'jackets',
  },
  {
    imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
    price: 325,
    id: 30,
    name: 'Camo Down Vest',
    productType: 'mens',
  },
  {
    id: 31,
    price: 20,
    name: 'Floral T-shirt',
    imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
    productType: 'mens',
  },
  {
    id: 32,
    imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
    name: 'Black & White Long sleeve',
    price: 25,
    productType: 'mens',
  },
  {
    price: 25,
    id: 33,
    imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
    name: 'Pink T-shirt',
    productType: 'mens',
  },
  {
    imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
    price: 40,
    name: 'Jean Long Sleeve',
    id: 34,
    productType: 'mens',
  },
  {
    id: 35,
    price: 25,
    name: 'Burgundy T-shirt',
    imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
    productType: 'mens',
  },
  {
    id: 10,
    imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
    price: 220,
    name: 'Adidas NMD',
    productType: 'sneakers',
  },
  {
    price: 280,
    imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
    name: 'Adidas Yeezy',
    id: 11,
    productType: 'sneakers',
  },
  {
    imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
    price: 110,
    id: 12,
    name: 'Black Converse',
    productType: 'sneakers',
  },
  {
    imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
    name: 'Nike White AirForce',
    price: 160,
    id: 13,
    productType: 'sneakers',
  },
  {
    imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
    price: 160,
    id: 14,
    name: 'Nike Red High Tops',
    productType: 'sneakers',
  },
  {
    id: 15,
    price: 160,
    imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
    name: 'Nike Brown High Tops',
    productType: 'sneakers',
  },
  {
    name: 'Air Jordan Limited',
    id: 16,
    price: 190,
    imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
    productType: 'sneakers',
  },
  {
    price: 200,
    imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
    name: 'Timberlands',
    id: 17,
    productType: 'sneakers',
  },
  {
    name: 'Blue Tank top',
    id: 23,
    imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
    price: 25,
    productType: 'womans',
  },
  {
    name: 'Floral Blouse',
    price: 20,
    imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
    id: 24,
    productType: 'womans',
  },
  {
    price: 80,
    imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
    name: 'Floral Dress',
    id: 25,
    productType: 'womans',
  },
  {
    name: 'Red Dots Dress',
    id: 26,
    price: 80,
    imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
    productType: 'womans',
  },
  {
    name: 'Striped Sweater',
    imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
    id: 27,
    price: 45,
    productType: 'womans',
  },
  {
    name: 'Yellow Track Suit',
    id: 28,
    price: 135,
    imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
    productType: 'womans',
  },
  {
    id: 29,
    name: 'White Blouse',
    imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
    price: 20,
    productType: 'womans',
  },
];
